on:
  push:
    tags:
      - '*'  # This will trigger the workflow on any tag push

name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout the branch (master or develop)
        run: git checkout develop

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: notes
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: develop  # Push to the develop branch or master
