name: Lint

on:
  push:
    paths:
      - '**/*.lua'
  pull_request:
    paths:
      - '**/*.lua'

jobs:
  lint:
    name: Stylua Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

