name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Neovim Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: Run Tests
        run: make test

